### ISSUE TITLE
Vtd overwrites symlinks with actual file

### ISSUE THREAD

**Issue by paulhybryant** [chiphogg/vim-vtd#19]
I symlinked my vtd file to my home directory so I can put all my stuff in a single place.

However whenever I changed the todo status in VtdView, the symlink is overwritten with the actual file.

**Comment by chiphogg** [comment]
Oops!

Can you provide specific instructions to reproduce?

(I've got a deadline today for the revision on a paper I'm writing, but I'll try to be as responsive as I can.)

**Comment by paulhybryant** [comment]
Thanks for replying while you are busy :).
Here are the steps to reproduce.

Create an vtd file, with valid content (foo.vtd)
ln -s foo.vtd bar.vtd (now bar.vtd is a symlink)
vi bar.vtd
Make some change (e.g. space to mark something as done)
exit vim

Now bar.vtd will be a file instead of a symlink

**Comment by chiphogg** [comment]
Those instructions don't seem right to me (for example, when editing `bar.vtd` as a file, `<Space>` won't mark off a task as done).  However, when I was trying to reproduce, I found a different bug. :P

1. Create a valid VTD file `foo.vtd` (as before).  Here is the content I used, as an example.

    ```
    # project
      @ Action
         * comment
    ```
2. `ln -s foo.vtd bar.vtd` (as before).
3. Change my `.vimrc` to include the following line:

    ```vim
    Glaive vtd files+=`expand('~/bar.vtd')`
    ```
4. Start vim, run `:VtdView`, and hit `X` to go to Next Actions.
5. Try checking off an action -- I can't!

So there's definitely a bug with symlinks.  I'll see if I can figure out what's going on and fix it.

**Comment by paulhybryant** [comment]
Hi,

Thanks for looking into the issue.

I am just curious why space does not work though. This is the output of
verbose map <SPACE> after opening a vtd file
n  <Space>     *@:call <SNR>281_CheckoffNextAction()<CR>
        Last set from ~/.vim/bundle/vim-vtd/autoload/vtd/view.vim

Thanks,

On Tue, Oct 20, 2015 at 9:34 AM, Chip Hogg <notifications@github.com> wrote:

> Those instructions don't seem right to me (for example, when editing
> bar.vtd as a file, <Space> won't mark off a task as done). However, when
> I was trying to reproduce, I found a different bug. :P
>
>    1.
>
>    Create a valid VTD file foo.vtd (as before). Here is the content I
>    used, as an example.
>
>    # project
>      @ Action
>         * comment
>
>    2. ln -s foo.vtd bar.vtd (as before).
>    3.
>
>    Change my .vimrc to include the following line:
>
>    Glaive vtd files+=`expand('~/bar.vtd')`
>
>    4. Start vim, run :VtdView, and hit X to go to Next Actions.
>    5. Try checking off an action -- I can't!
>
> So there's definitely a bug with symlinks. I'll see if I can figure out
> what's going on and fix it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chiphogg/vim-vtd/issues/19#issuecomment-149394999>.
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Comment by chiphogg** [comment]
Just a hunch -- when you say "opening a vtd file", do you mean running `:VtdView`?

When I'm in the VtdView buffer, I get exactly what you get for `:verbose map <SPACE>` (well, apart from a different script number).  But when I open the `.vtd` file itself, I don't have any such mapping.

**Comment by paulhybryant** [comment]
Sorry I should have been more explicit. By opening a vtd file I mean open
it with vi and run :VtdView. I have an autocmd to do this so I didn't
mentioned that.

Thanks,

On Sun, Oct 25, 2015 at 9:47 PM, Chip Hogg <notifications@github.com> wrote:

> Just a hunch -- when you say "opening a vtd file", do you mean running
> :VtdView?
>
> When I'm in the VtdView buffer, I get exactly what you get for :verbose
> map <SPACE> (well, apart from a different script number). But when I open
> the .vtd file itself, I don't have any such mapping.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chiphogg/vim-vtd/issues/19#issuecomment-150924344>.
>



-- 
With Regards,

Yu Huang

Software Engineer,
Google Inc.

**Comment by chiphogg** [comment]
I figured the `patch` command was probably the root of this, so I tested running a bare patch command on some test files.  When I tried applying a patch to the symlink, I got this:

```
File link is not a regular file -- refusing to patch
1 out of 1 hunk ignored -- saving rejects to file link.rej
```

The following snippet from `man patch` seems relevant:

```
       --follow-symlinks
          When looking for input files, follow symbolic links.   Replaces  the
          symbolic  links,  instead  of modifying the files the symbolic links
          point to.  Git-style patches to symbolic links will no longer apply.
          This  option  exists  for backwards compatibility with previous ver‐
          sions of patch; its use is discouraged.
```

It may be that `patch` sets this option for you, but doesn't set it for me.  That could explain both the behaviour that you've seen, and the behaviour that I've seen.

In any case: I think I know how to fix this.  I should have a patch (heh) coming soon.
