### ISSUE TITLE
Install with NeoBundle

### ISSUE THREAD

**Issue by dfroger** [chiphogg/vim-vtd#20]
I follow the [instructions](https://github.com/chiphogg/vim-vtd#neobundle) for NeoBundle, but I get the error message: 

    E117: Unknown function: glaive#Install

**Comment by chiphogg** [comment]
You're right!  I can reproduce.  Let me get a commit out to fix the instructions.

**Comment by dfroger** [comment]
Thanks! vim-vtd is great!

**Comment by chiphogg** [comment]
Thank you!  I am delighted that you find it useful.
