### ISSUE TITLE
Please add install instructions for vim-plug

### ISSUE THREAD

**Issue by ghost** [chiphogg/vim-vtd#33]
I am using vim 8.1.1486 with vim-plug (https://github.com/junegunn/vim-plug) as plugin manager and I'm having troubles installing vim-vdt.

Relevant part of my .vimrc:

    " vim-vdt (GDT plugin)                                                          
    Plug 'google/maktaba'                                                           
    Plug 'google/glaive', {'do': ':call glaive#Install()'}                          
    Plug 'chiphogg/vim-vtd

vim-plug supports post-install/update hooks: https://github.com/junegunn/vim-plug/blob/master/doc/plug.txt#L292

The glaive install function succeeds, because once I do

    :PlugUpdate

and it completes, I see:

    Post-update hook for glaive ... OK

During install, vim-vdt also seems to successfully pull his dependencies that are linked as git submodules, according to the log:

    Submodule 'python/libvtd' (https://github.com/chiphogg/libvtd.git) registered for path 'python/libvtd'
    Cloning into '/home/user/.vim/plugged/vim-vtd/python/libvtd'...
    Submodule path 'python/libvtd': checked out 'b93be3f1bacb2d9289042a4d090fb789de48ba5e'
    Submodule 'third_party/dateutil' (https://github.com/dateutil/dateutil.git) registered for path 'python/libvtd/third_party/dateutil'
    Cloning into '/home/user/.vim/plugged/vim-vtd/python/libvtd/third_party/dateutil'...
    Submodule path 'python/libvtd/third_party/dateutil': checked out '03fa92bfedbe020724de5dde8864e3a9539162b4'

But something is wrong after that:

1. While /home/user/.vim/plugged/vim-vdt/doc/ gets a tags file, which means that vim-plug has indeed visited and processed that directory, because it automatically builds docs for all plugins it installs, when I type

    :h vdt

in vim, I get an error:

    E149: Sorry, no help for vdt

2. vim-vdt related commands are not available in vim:

    :VtdView
    E492: Not an editor command: VdtView

**Comment by chiphogg** [comment]
Sometimes you have typed `vtd`, sometimes `vdt`.  I just want to clarify: are the `vdt` instances typos in this post only?  Or were you really typing `vdt`?

**Comment by ghost** [comment]
Thanks for the quick reply and for pointing to my mistake.

My fault entirely, I was mistyping the commands instead of copypasting them from the docs (typing helps me learn them faster).

Both :h vtd and :VtdView work now.

**Comment by chiphogg** [comment]
I do that too!  (Typing to learn.)

Glad it worked out for you, and enjoy the plugin!
